<?php

function varql_views_api() {
  return array(
    'api' => '3.0-alpha1',
    'path' => drupal_get_path('module', 'varql'),
  );
  return '3.0-alpha1';
}

function _varql_get_namespaces() {
  $rdf_namespaces = &drupal_static(__FUNCTION__);
  if (empty($rdf_namespaces)) {
    $rdf_namespaces = module_invoke_all('rdf_namespaces');
    foreach($rdf_namespaces as $ns => $url) {
      if(is_array($url)) {
        $rdf_namespaces[$ns] = $url[0];
      }
    }
  }
  // @todo ensure there are no duplicates and that array is only one level.
  return $rdf_namespaces;
}

function varql_rdf_namespaces() {
  return array(
    'dbpedia-owl' => 'http://dbpedia.org/ontology/',
  );
}

function _predicate_ns($predicate) {
  $split = explode(':', $predicate);
  if(count($split) == 2)
    return $split[0];
  return FALSE; 
}
